// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateWallet(arg1, arg2) {
  return window['go']['main']['App']['CreateWallet'](arg1, arg2);
}

export function EstimateGas(arg1, arg2, arg3) {
  return window['go']['main']['App']['EstimateGas'](arg1, arg2, arg3);
}

export function GetAssets(arg1) {
  return window['go']['main']['App']['GetAssets'](arg1);
}

export function GetTransactions(arg1) {
  return window['go']['main']['App']['GetTransactions'](arg1);
}

export function RecoverWallet(arg1, arg2) {
  return window['go']['main']['App']['RecoverWallet'](arg1, arg2);
}

export function RestoreWallet(arg1, arg2, arg3) {
  return window['go']['main']['App']['RestoreWallet'](arg1, arg2, arg3);
}

export function SendTransaction(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendTransaction'](arg1, arg2, arg3, arg4);
}

export function ValidateAddress(arg1, arg2) {
  return window['go']['main']['App']['ValidateAddress'](arg1, arg2);
}

export function ValidateMnemonic(arg1) {
  return window['go']['main']['App']['ValidateMnemonic'](arg1);
}

export function WalletExists() {
  return window['go']['main']['App']['WalletExists']();
}
