// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateWallet(arg1) {
  return window['go']['main']['App']['CreateWallet'](arg1);
}

export function ValidateMnemonic(arg1) {
  return window['go']['main']['App']['ValidateMnemonic'](arg1);
}
