// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateWallet(arg1:string):Promise<string>;

export function GetAssets(arg1:Array<string>):Promise<{[key: string]: number}>;

export function RestoreWallet(arg1:string,arg2:string):Promise<void>;

export function ValidateMnemonic(arg1:string):Promise<boolean>;

export function WalletExists():Promise<boolean>;
