// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {hdwallet} from '../models';

export function CreateWallet(arg1:Array<string>,arg2:string):Promise<string>;

export function EstimateGas(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetAssets(arg1:Array<string>):Promise<{[key: string]: number}>;

export function GetTransactions(arg1:string):Promise<Array<hdwallet.WalletTransaction>>;

export function RecoverWallet(arg1:Array<string>,arg2:string):Promise<void>;

export function RestoreWallet(arg1:Array<string>,arg2:string,arg3:string):Promise<void>;

export function SendTransaction(arg1:string,arg2:string,arg3:string,arg4:string):Promise<boolean>;

export function ValidateAddress(arg1:string,arg2:string):Promise<boolean>;

export function ValidateMnemonic(arg1:string):Promise<boolean>;

export function WalletExists():Promise<boolean>;
